BACKPACK_AUTH:
  DEFAULT_WINDOW: 5000

BACKPACK_API_URL: https://api.backpack.exchange/
BACKPACK_WS_URL: wss://ws.backpack.exchange/

HYPERLIQUID_API_URL: https://api.hyperliquid.xyz

LOG_FILE_PATH: logs/arbitrage.log

# Arbitrage Engine Configuration
POSITION_SIZE: 60.0
MIN_RATE_DIFFERENCE: 0.0001
MIN_HOLD_TIME_SECONDS: 3600
MAGNITUDE_REDUCTION_THRESHOLD: 0.1
CHECK_INTERVAL_MINUTES: 30
MAX_CONCURRENT_POSITIONS: 1